receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    # A CORREÇÃO FINAL ESTÁ AQUI: Adicionamos o "http://"
    endpoint: http://jaeger:4318
    tls:
      insecure: true

  debug:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]